name: Milpa Netzwerk Prototyp
theme: jekyll-theme-minima
title: Milpa-Netzwerk Webplattform
paragraph-1: Diese Seite dient als Prototyp für ein Online-Projekt des Kollektivs Tonalli und zeigt einige Standorte auf einer Karte, an denen unsere Partner in Deutschland eine Milpa angelegt haben. Diese Orte bieten Treffpunkte, an denen es möglich ist, von dieser alten mesoamerikanischen landwirtschaftlichen Tradition zu lernen, sowie Samen und Wissen über den Anbau von Mais, Bohnen, Kürbis, Chili, Tomatillos und anderen Milpa-Pflanzen auf europäischem Boden auszutauschen.
paragraph-2: Der Mais wurde erstmals in Mexiko, in der Nähe von der Stadt Tehuacán im Bundesstaat Puebla, vor fast 9000 Jahren gesät. Er wurde aus einem Wildgras namens Teocintle entwickelt, und für die indigenen Völker Mesoamerikas hatte er eine mythologische Bedeutung. Für sie wurde der Mensch laut Überlieferung von den Göttern aus Mais geformt und war somit eng mit der Erde und ihren Erträgen verbunden. Die Milpa wurde als bevorzugtes landwirtschaftliches System von der Olmeca-, Maya- und Mexica-Kulturen entwickelt und über Jahrtausende auf dem gesamten amerikanischen Kontinent weitergegeben. Als die Spanier zum ersten Mal in Amerika landeten war die Milpa bereits weit verbreitet, von Argentinien bis Kanada. In dieser Zeit gelangte der Mais nach Südeuropa, insbesondere in die Mittelmeerländer, und verbreitete sich von dort aus langsam, aber stetig nach Norden, Süden und Osten. Heutzutage ist der Mais in europäischen, afrikanischen und asiatischen Kulturen fest verwurzelt und stellt ein wichtiges Nahrungsmittel dar. Oft wird er jedoch vor allem für die Tierfütterung genutzt und dient zudem als Grundlage für Biogas, biologisch abbaubaren Kunststoff und andere industrielle Produkte.
paragraph-3: Trotzdem galt Mais in Europa historisch als minderwertiges Lebensmittel im Vergleich zu einheimischem Getreide wie Weizen und Roggen. Als der Mais aus seiner Ursprungsland, und in die Welt zu Anfang der Globalisierung transplantiert wurde, verlor er seinen mesoamerikanischen kulturellen Kontext. Dort wird er vor dem Verzehr traditionell in einer Brühe aus Wasser und Kalk gekocht. Dieser Prozess heißt Nixtamalisation, und ohne ihn, kann der Verzehr von Mais gesundheitsschädlich sein und eine Krankheit namens Pellagra verursachen. Eine Reihe von Hungersnöten und Epidemien in Südeuropa zwischen dem 16. und 19. Jahrhundert trug zu dem bis heute bestehenden Vorurteil gegenüber Mais bei.
paragraph-4: Da der Anbau und die Nutzung von Mais in der globalisierten Welt heute weit von den tief verwurzelten und nachhaltigen Traditionen des amerikanischen Kontinents entfernt sind, hat sich das Projekt Maíz zum Ziel gesetzt, Online-Werkzeuge und Plattformen zu schaffen, die es Nutzer*innen ermöglichen, tiefer in das Thema Mais und Milpa einzutauchen, sich mit anderen Menschen in ihrer Nähe zu vernetzen und mehr über diese faszinierende Anbaumethode zu lernen.

# Another possibility to set Jekyll configuration options
# site configuration

theme: jekyll-theme-chirpy

lang: en

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: Corey Goldberg

# subtitle
tagline: Blog

# used by seo meta and the atom feed
description: Blog by Corey Goldberg

# protocol & hostname for your site (it does not end with a '/')
url: https://cgoldberg.github.io

author:
  name: Corey Goldberg
  # sets the `author.url` property. helps Google to disambiguate the correct author of articles
  url: https://github.com/cgoldberg

# URL to a site-wide logo (e.g.: /assets/your-company-logo.png)
#logo:

github:
  username: cgoldberg

#twitter:
#  username: cgoldberg

social:
  # displayed as the default author of the posts and the copyright owner in the footer
  name: Corey Goldberg
  #email: example@domain.com
  links:
    # first element serves as the copyright owner's link
    - https://github.com/cgoldberg
    - https://www.linkedin.com/in/cgoldberg
    # uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://twitter.com/username

webmaster_verifications:
  google: U9-hCLAR44wY-5vEZSfl8iVgClFj5L0nuUgP8pdl2xo
  #  bing: # fill in your Bing verification code
  #  alexa: # fill in your Alexa verification code
  #  yandex: # fill in your Yandex verification code
  #  baidu: # fill in your Baidu verification code
  #  facebook: # fill in your Facebook verification code

# end of `jekyll-seo-tag` settings

# web analytics settings
analytics:
  google:
    id: G-VDZPG2HGL4
#  goatcounter:
#    id: # fill in your GoatCounter ID
#  umami:
#    id: # fill in your Umami ID
#    domain: # fill in your Umami domain
#  matomo:
#    id: # fill in your Matomo ID
#    domain: # fill in your Matomo domain
#  cloudflare:
#    id: # fill in your Cloudflare Web Analytics token
#  fathom:
#    id: # fill in your Fathom Site ID

# page views settings
#pageviews:
#  provider: # only supports 'goatcounter'

# color scheme setting
# note: empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark
# and light on the bottom left of the sidebar.
# available options: light, dark
theme_mode: dark

# CDN endpoint for media resources
# note: once assigned, the CDN URL will be added to all media resource paths
# starting with '/' (site avatar, post images, audio files, video files)
# e.g. 'https://cdn.com'
#cdn:

# avatar on sidebar (supports local or CORS resources)
avatar: /assets/img/corey_goldberg.jpg

# URL of the site-wide social preview image used in SEO `og:image` meta tag.
# it can be overridden by a customized `page.image` in front matter.
#social_preview_image: # string, local or CORS resources

# global switch for TOC in posts (boolean)
toc: false

#comments:
  # global switch for the post-comment system. empty means disabled.
  #provider: disqus # [disqus | utterances | giscus]
  # provider options are as follows:
  #› https://disqus.com/
  #disqus:
  #  shortname: cgoldberg
  #› https://utteranc.es
  #utterances:
  #  repo: # <gh-username>/<repo>
  #  issue_term: # < url | pathname | title | ...>
  #› https://giscus.app
  #giscus:
  #  repo: # <gh-username>/<repo>
  #  repo_id:
  #  category:
  #  category_id:
  #  mapping: # optional, default to 'pathname'
  #  strict: # optional, default to '0'
  #  input_position: # optional, default to 'bottom'
  #  lang: # optional, default to the value of `site.lang`
  #  reactions_enabled: # optional, default to the value of `1`

# self-hosted static assets (optional) › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: false # boolean, empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

#pwa:
#  enabled: true # The option for PWA feature (installable)
#  cache:
#    enabled: true # The option for PWA offline cache
#    # paths defined here will be excluded from the PWA cache.
#    # usually its value is the `baseurl` of another website that
#    # shares the same domain name as the current website.
#    deny_paths:
#      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# base URL of your site
baseurl: ""

# default site-wide value for all pages
defaults:
  - scope:
      path: "" # empty string means all files
    values:
      seo_description_max_words: 200

# ------------ following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    tag: tag
    category: category
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/